name    'nholuongut-ruby'
version '2.0.13'
author  'Nho Luong'
license 'Apache2'
project_page 'https://github.com/nholuongut'
source  'https://github.com/nholuongut/puppet-ruby'
summary 'Puppet module for ruby'
description 'This module installs and manages ruby. Check README for details.'
dependency 'nholuongut/puppi', '>= 2.0.0'
# dependency 'nholuongut/monitor', '>= 2.0.0'
# dependency 'nholuongut/firewall', '>= 2.0.0'
